esphome:
  name: motor-control
  friendly_name: motor control
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:  
  password: !secret api_password

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

wifi:
  # Set up a wifi access point using the device name above
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "motor_control_hotspot"
    password: !secret wifi_ap_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:
    
web_server:
  port: 80 
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Sensor IP address"
    ssid:
      name: "Sensor SSID"
  - platform: version
    name: "Sensor ESPHome Version"

output:
  - platform: gpio
    id: motor_forward_pin
    pin: GPIO5
  - platform: gpio
    id: motor_reverse_pin
    pin: GPIO4
  - platform: gpio
    id: motor_enable_pin
    pin: GPIO12

cover:
  - platform: time_based
    name: "door cover"

    open_action:
      - switch.turn_on: motor_forward_pin
      - switch.turn_on: motor_enable_pin
    open_duration: 2.1min

    close_action:
      - switch.turn_on: motor_reverse_pin
      - switch.turn_on: motor_enable_pin
    close_duration: 2min

    stop_action:
      - switch.turn_off: motor_enable_pin