esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: esphome.motor-control
    version: dev # This will be replaced by the github workflows with the `release` version
