name: Build and Publish

on:
  push:
    branches:
      - main
    paths: 
      - '**/project.yaml'
      - '*.yaml'
      - '.github/workflows/esphome.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - project

        esphome-version:
          - stable

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}
      - name: ESPHome ${{ matrix.esphome-version }} Factory
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}.factory.yaml
          version: ${{ matrix.esphome-version }}
